### PR TITLE
Added ms-Fabric to Taskpane.html body style

### LINKED ISSUE #23: Body doesn't have ms-Fabric style
I loaded this addin to Excel, and I noticed that the style doesn't look right. In particular, the standard browser font is being used. I expected it to use Segoe UI Web.

I noticed that [Office-Addin-TaskPane/src/taskpane/taskpane.html#L23](https://github.com/OfficeDev/Office-Addin-TaskPane/blob/463fcd847321faf54581b844375ff4a3161a116a/src/taskpane/taskpane.html#L23) applies the ms-Fabric style to `body` which specifies the Segoe UI Web font family.

Does Office-Addin-TaskPane-React intentionally not use Segoe UI Web nor ms-Fabric?

### PR DESCRIPTION
**Pull request by rob-deutsch**
I am not 100% sure if this is correct. I am not terribly familiar with React/CSS nor the author's intention.

On macOS Excel 365 the style of the taskpane does not seem correct. In particular the fonts seem incorrect. The fonts appear correct in OfficeDev/Office-Addin-TaskPane and are applied by the [ms-Fabric class](https://github.com/OfficeDev/Office-Addin-TaskPane/blob/463fcd847321faf54581b844375ff4a3161a116a/src/taskpane/taskpane.html#L23).

Maybe fixes #23

### CODE REVIEW

**Comment by akrantz** [comment]
Thanks @rob-deutsch. We'll take a look.

**Comment by TCourtneyOwen** [comment]
Tested the PR on Windows and Mac and the taskpane display looks good.  Not a dramatic difference, but I agree that we should remain consistent with Office-Addin-Taskpane

**Comment by akrantz** [comment]
@rob-deutsch You need to sign the Contributor License Agreement.

**Comment by rob-deutsch** [comment]
Just to confirm; I have signed the CLA.

**Pull request merged**
