### PR TITLE
Merge office addin taskpane

### PR DESCRIPTION
**Pull request by TCourtneyOwen**

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
I removed a couple failing builds from the pipeline - going to close and re-open PR to see if that kickstarts the CI pipeline again. I am guessing no but worth a shot

**Comment by TCourtneyOwen** [comment]
that did in fact kickstart the pipeline

**Comment by akrantz** [comment]
I wonder if it might be based on whether the branch is up-to-date with master or not. Did pushing the last commit to merge master not kick it off, and it only got kicked off after close and reopen of the PR?

**Comment by akrantz** [comment]
is it kicking of a build if another commit is pushed?

**Comment by TCourtneyOwen** [comment]
It should have – there’s definitely something not right here

**Pull request merged**
