### PR TITLE
Ui tests

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
Validated convertToSingleHost with "convert-test" param creates test infra targeted to specific host

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
Need to investigate test failure on Mac

**Comment by akrantz** [comment]
I'll wait to review until Mac is working.

**Comment by TCourtneyOwen** [comment]
I think I have the fix for the Mac issue - a problem with a change I made to getProcessId in test/testHelpers.ts

**Comment by TCourtneyOwen** [comment]
Tests now pass on Windows and Mac with latest commit

**Comment by akrantz** [comment]
I think you need to rebase this because the test code was squashed into one commit. We want to merge the other commits but not include all 58 commits. We can discuss in person.

**Comment by TCourtneyOwen** [comment]
Abandoning this PR and opening a new one that won't be as cluttered up with numerous commits

**Pull request closed without merging**
