### PR TITLE
Merge office addin taskpane

### PR DESCRIPTION
**Pull request by TCourtneyOwen**

### CODE REVIEW

**Comment by akrantz** [comment]
@TCourtneyOwen This mac agent for this CI is not correct. It is not actually using the mac pool.

**Comment by akrantz** [comment]
Please go through all of the CI pipelines and make sure they are correct.

**Comment by TCourtneyOwen** [comment]
Pipeline is fixed now.  Went through the other pipelines as well and found a couple other issues I fixed

**Comment by akrantz** [comment]
Thanks!

**Pull request closed without merging**
